theme: jekyll-theme-modernist
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Food"
description: "Food games and recipes"
gitorg: https://github.com/RyanHaki/Final
google_analytics: